FROM golang:1.12.0-alpine3.9
 
# RUN apk add --no-cache git
RUN apk add git
 
ENV GO111MODULE=on
 
ENV PORT=9091
 
WORKDIR /app
 
COPY go.mod .
 
COPY go.sum .
 
RUN go mod download
 
COPY . .
 
RUN go build
 
CMD ["/app/hello-app"]
